name:                batcher
version:             0.1.0.0
github:              "sukovanej/batcher"
license:             BSD3
author:              "Milan Suk"
maintainer:          "Milansuk@email.cz"
copyright:           "2022 Milan Suk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sukovanej/batcher#readme>

dependencies:
- base >= 4.7 && < 5
- amqp
- bytestring
- text
- warp
- wai
- aeson
- http-types
- hedis
- containers
- random
- mtl

library:
  source-dirs: src

executables:
  batcher-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - batcher

tests:
  batcher-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - batcher
